# Generated by Django 2.0.3 on 2018-06-12 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180320_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='secure_hash',
            field=models.CharField(default='a3699147a8f08a9bfc203f5b2ed28c27e553d550efcf987965b657aaa000cf4f', max_length=64),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SensorType', verbose_name='Tipo'),
        ),
    ]
