# Generated by Django 2.0.3 on 2018-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180612_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='secure_hash',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
